# Generated by Django 4.2 on 2023-05-03 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_artista_usuario_delete_usuarios_artista_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('esproductor', models.BooleanField(verbose_name='True')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='repeat_password',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Artista',
        ),
        migrations.AddField(
            model_name='tipo_usuario',
            name='tipo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.usuario'),
        ),
    ]
